config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

get '/login', to: 'sessions#new'
delete '/logout', to: 'sessions#destroy'
post '/login', to: 'sessions#create'
get '/signup', to: 'users#new'
post '/member', to:'users#member'
resources :users
resources :posts



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	
	attr_accessor :remember_token
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates(:name, presence:true,length:{maximum:50})
	validates(:email, presence:true, length:{maximum:255}, format:{with:VALID_EMAIL_REGEX}, uniqueness:{case_sensitive:false})
	validates(:password, presence:true, length:{minimum:3}, allow_nil:true)


	def self.create_token
		SecureRandom.urlsafe_base64
	end

	def self.encrypt token
		BCrypt::Password.create(token)
	end

	def remember
		self.remember_token = User.create_token
		self.update_attributes(remember_digest: User.encrypt(remember_token))
	end

	def authenticate? token
		digest = self.remember_digest
		BCrypt::Password.new(digest).is_password?(token)
	end

	def mk_admin
		self.update_attribute(:admin, true)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login user
  	session[:user_id] = user.id
  end

  def is_logged_in?
  	if session[:user_id]  || remember_option
  		return true
  	end
  end

   def current_user
      user = User.find_by(id: session[:user_id])
   end

   def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent.signed[:remember] = user.remember_token
   end

   def forget user 
    cookies.delete(:user_id)
    cookies.delete(:remember)
   end


   def remember_option
    user =  User.find_by(id:cookies.signed[:user_id])
    if  user && user.authenticate?(cookies.signed[:remember])
      session[:user_id] = user.id
    end
   end

  helper_method :is_logged_in?, :current_user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_actoion :is_logged_in?, only:[:new, :create]
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
  	if @post.save
  		flash[:success] = "You have create a new post"
  		redirect_to posts_url
  	else
  		render 'new'
    end
  end

  def index
  	@posts = Post.all
  end



  private

  def post_params
  	params.require(:post).permit(:title,:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  	  login @user

  	  params[:session][:remember] == '1'? remember(@user) : forget(@user)
  	
  	  flash[:success] = "Succesful login"
      redirect_to @user
  	else
  		flash[:fail] = "Wrong credentials"
  		render 'new'
  	end
  end

  def destroy
  	forget current_user
  	session[:user_id] = nil
  	redirect_to users_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :is_logged_in_as_admin?, only: [:destroy,:member,:edit]



	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			@user.mk_admin if params[:user][:admin] == '1'
			login @user
			flash[:success] = "User has been created"
			redirect_to @user
		else
			render 'new'
		end
	end

	def index
		@users = User.all
	end

	def show
	  @user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if  @user.update_attributes(user_params)
			@user.mk_admin if params[:user][:admin] == '1'
			flash[:success] = "User has been updated"
			redirect_to @user
		else
			render 'edit'
		end

	end

	def destroy
		@user.delete
		flash[:success] = "User has been deleted"
		redirect_to users_path

	end

	def member 
		user = User.find(params[:user])
		user.update_attribute(:member,:true)
		redirect_to users_path
	end


	private

	def user_params
		params.require(:user).permit(:name,:email,:password,:password_confirmation)
	end

	def is_logged_in_as_admin?
		unless is_logged_in? && current_user.admin
			flash[:fail] = "NOt ALLOWED"
			redirect_to users_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if is_logged_in? %>
     <h1>Logged in <%= current_user.name %></h1>
     <%= link_to 'logout',  logout_path, method: :delete %>
     <% end %>
  <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <ul style="border:1px solid black">
  	<h4>Title</h4>
   	<li> <%= post.title %> </li>
  	<h4>Body</h4>
	<li> <%= post.body  %></li>
	
		<% if current_user && current_user.member %>
  	    <h4>Author</h4>
		<li> by <%=  User.find(post.user_id).name  %> </li>
		<% end %>


  </ul>	
	
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% @post.errors.full_messages.each do |msg| %>
  <li> <%= msg %> </li>
<% end %>

<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %></br>
<%= f.label :body %>
<%= f.text_area :body %>
<%= f.submit %>
<% end %>

app/views/shared/_error_messages.html.erb
<% @user.errors.full_messages.each do |msg| %>
  <li> <%= msg %> </li>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key,value| %>
	<%= content_tag(:div,value, :class => "flash #{key}") %>
<% end %>

app/views/shared/_form.html.erb
<%= render 'shared/error_messages' if @user.errors.any? %>
<%= form_for @user do |f| %>
  <%= f.label :name %> 
  <%= f.text_field :name %></br>
  <%= f.label :email %>
  <%= f.email_field :email %></br>
  <%= f.label :password %>
  <%= f.password_field :password %></br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></br>
  <%= f.label :admin %>
  <%= f.check_box :admin %> </br>
  <%= f.submit :submit %>
 <% end %>

app/views/users/edit.html.erb
<h1> Edit user</h1>

  <%= render 'shared/form' %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <li><%= user.name %>
  <%= user.email %>
  <%= user.member ? "Member": "Non-Member" %>

  <% if current_user && current_user.admin %>
    <%= link_to 'delete', user, :method=>:delete %>
  
    <%= link_to 'member', member_url(:user => user), :method=>:post unless user.member %></li>
  <% end %>

<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user do |f|%>
  <%= render 'shared/form' %>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.name %> </h3>
<h3><%= @user.email %></h3>